#!/bin/bash

# Cloudwijk Deployment Script
echo "🚀 Cloudwijk Deployment Helper"
echo "================================"
echo ""
echo "📝 Stap 1: Maak eerst een GitHub repository aan op github.com/new"
echo "   - Naam: cloudwijk"
echo "   - NIET initialiseren met README"
echo ""
echo "📤 Stap 2: Run deze commando's (vervang YOUR_GITHUB_USERNAME):"
echo ""
echo "git remote add origin https://github.com/YOUR_GITHUB_USERNAME/cloudwijk.git"
echo "git push -u origin main"
echo ""
echo "🔗 Stap 3: Deploy naar Vercel:"
echo "   Ga naar: https://vercel.com/new"
echo "   - Import je cloudwijk repository"
echo "   - Framework: Next.js (auto-detected)"
echo "   - Root Directory: ./ (leave default)"
echo ""
echo "🔐 Stap 4: Environment Variables in Vercel toevoegen:"
echo ""
echo "VEREIST (deze 4 MOET je hebben):"
echo "----------------------------------------"
echo "NEXT_PUBLIC_SUPABASE_URL="
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY="
echo "SUPABASE_SERVICE_ROLE_KEY="
echo "RESEND_API_KEY="
echo ""
echo "OPTIONEEL (voor extra features):"
echo "----------------------------------------"
echo "NEXTAUTH_SECRET=$(openssl rand -base64 32)"
echo "ADMIN_EMAILS=jouw-email@example.com"
echo "NEXT_PUBLIC_APP_URL=https://cloudwijk.vercel.app"
echo ""
echo "📊 Stap 5: Supabase Setup:"
echo "   1. Ga naar https://supabase.com"
echo "   2. Create New Project"
echo "   3. Ga naar SQL Editor"
echo "   4. Plak de inhoud van: supabase/migrations/20240101000000_initial_schema.sql"
echo "   5. Run de migration"
echo "   6. Kopieer je project URL en keys naar Vercel"
echo ""
echo "📧 Stap 6: Resend Setup:"
echo "   1. Ga naar https://resend.com"
echo "   2. Sign up / Login"
echo "   3. Get API Key"
echo "   4. Plak in Vercel environment variables"
echo ""
echo "✅ Klaar! Je site is live op: https://[jouw-project].vercel.app"
echo ""
echo "Test URLs:"
echo "  - Homepage: https://[jouw-project].vercel.app"
echo "  - AI Act Checker: https://[jouw-project].vercel.app/ai-act-checker"
echo "  - Health Check: https://[jouw-project].vercel.app/api/health"
echo "  - Setup Status: https://[jouw-project].vercel.app/admin/setup-status"